name: Bug Report
description: Report an issue in JuspayKit
labels: ['bug']
body:
  - type: markdown
    attributes: 
      value: |
        🚀 Thank you for reporting an issue! Your feedback helps improve JuspayKit.
  - type: input
    id: summary
    attributes:
      label: Issue Summary
      description: 'A clear and concise one-line description of the problem.'
      placeholder: 'Briefly describe the issue'
    validations:
      required: true
  - type: input
    id: juspaykit-version
    attributes:
      label: JuspayKit Version
      description: 'The version of JuspayKit you are using.'
      placeholder: '1.x.x'
    validations:
      required: true
  - type: input
    id: swift-version
    attributes:
      label: Swift Version
      description: 'The version of Swift you are using.'
      placeholder: 'Swift 5.8'
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform and Version
      description: 'The platform and version you are using (e.g., iOS 16.5, macOS 13.4).'
      placeholder: 'iOS 16.5'
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: 'How can we reproduce this issue? Please be as detailed as possible.'
      placeholder: |
        1. Initialize JuspayClient with...
        2. Call method X with parameters...
        3. ...
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: 'What did you expect to happen?'
      placeholder: 'The method should return...'
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: 'What actually happened?'
      placeholder: 'Instead, the method threw an error...'
  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: 'If possible, provide a minimal code sample that demonstrates the issue.'
      render: swift
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: 'Any other context about the problem? (logs, screenshots, etc.)'